# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on: push
#on:
#  push:
#    tags:
#      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Download FFmpeg
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output
        with:
          url: "https://github.com/ShareX/FFmpeg/releases/download/v4.3.1/ffmpeg-4.3.1-win64.zip"
          target: win32-x64.zip

      - name: Unzip FFmpeg
        uses: montudor/action-zip@v1
        with:
          args: unzip -o -d . -j win32-x64.zip 'ffmpeg.exe'

      - name: PyInstaller Windows
        run: |
          docker run --entrypoint /bin/sh --rm -v $GITHUB_WORKSPACE:/src cdrx/pyinstaller-windows:latest -c "python -m pip install --upgrade pip && /entrypoint.sh"
#          docker run -v $GITHUB_WORKSPACE:/src cdrx/pyinstaller-windows:latest 'pyinstaller -F --clean -y --dist ./ --workpath /tmp main.py'

#      - name: release
#        uses: actions/create-release@v1
#        id: create_release
#        with:
#          draft: false
#          prerelease: false
#          release_name: ${{ github.ref }}
#          tag_name: ${{ github.ref }}
#          body_path: CHANGELOG.md
#        env:
#          GITHUB_TOKEN: ${{ github.token }}

#      - name: upload Windows artifact
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./main.exe
#          asset_name: main.exe
#          asset_content_type: application/octet-stream